[font]
size = 18.0

[font.bold]
# family = "Cica"
# style = "Bod"

[font.normal]
# family = "Cica"
# style = "Regular"
family = "Hack Nerd Font Mono"

[font.offset]
y = 1

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 8
y = 4

[window]
opacity = 0.95
